config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :organizations # , :only => [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/searchorg', :to => 'organizations#search'
  match '/createorg',  :to => 'organizations#new'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :address, :url
  belongs_to :user
  has_many :socialmedialinks

  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }

  def self.search(search)
    if search
      find(:all, :conditions => ['name ILIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
 before_filter :signed_in_user,
                 :only => [:index, :edit, :update, :create]
  before_filter :correct_user, :only => [:edit, :update]

  def search
    @name = params[:name]
    @results = Organization.search(@name)
    @organizations = @results.paginate(page: params[:page], per_page: 10)
  end

  def show
    @organization = Organization.find(params[:id])
    @name = @organization.name
    @address = @organization.address
    @url = @organization.url
  end

  def new
    @organization  = Organization.new
    @title = "Create your organization"
  end

  def edit
    @title = "Edit organization"
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    if @organization.update_attributes(params[:organization])
      redirect_to @organization, :flash => { :success => "Profile updated." }
    else
      @title = "Edit organization"
      render 'edit'
    end
  end

 def create
    @organization = current_user.organizations.build(params[:organization])
    if @organization.save
      redirect_to @organization, :flash => { :success => "Organization created!" }
    else
      render 'pages/home'
    end
  end

  private

    def correct_user
      @organization = Organization.find(params[:id])
      redirect_to(root_path, :flash => { :error => "The organization you tried to edit does not belong to you!" }) unless current_user?(@organization.user)
    end

end

app/views/organizations/_fields.html.erb
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :address %><br />
  <%= f.text_field :address %>
</div>
<div class="field">
  <%= f.label :url %><br />
  <%= f.url_field :url %>
</div>

app/views/organizations/_organization.html.erb
    <span class="name">
      <%= link_to organization.name, organization %>
      <% if current_user?(organization.user) %>
        <%= link_to "Edit", edit_organization_path(organization), :class => "editlink" %>
      <% end %>
    </span>
    <span class="address"><%= organization.address %></span>
    <span class="url"><%= link_to organization.url, organization.url  %></span>

app/views/organizations/edit.html.erb
<h1>Edit organization</h1>

<div class="row">
  <div class="span6 offset3">
<%= form_for(@organization) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
  </div>
</div>

app/views/organizations/new.html.erb
<h1>Create your organization</h1>

<div class="row">
  <div class="span6 offset3">
<%= form_for(@organization) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>
 </div>
</div>

app/views/organizations/search.html.erb
<%= render 'shared/search_org_form' %>
<div class="row">
<% if @organizations.any? %>
 <div class="span8">
        <ol class="organizations">
          <%= render @organizations %>
        </ol>
  </div>
  <%= will_paginate @organizations %>
<% else %>
No Results matching that query
<% end %>
</div>

app/views/organizations/show.html.erb
<div class="row">
  <div class="span8">
        <ol class="organizations">
          <%= render @organization %>
        </ol>
  </div>
</div>